### ISSUE TITLE
Save/Load Drawings: Save your canvas state locally and reload it anytime.  

### ISSUE THREAD

**Issue by Aayushgoyal00** [MSTC-DA-IICT/Hacktoberfest24-Drawing-Canvas-React#5]
Implement saving and loading canvas data using LocalStorage or IndexedDB to persist the drawing state even after closing the browser.

**Comment by kavya020805** [comment]
Please assign the issue to me. 
It can be fixed by storing the canvas in LocalStorage using setItem. I also saved the selected color before the browser was reloaded or closed. Get the drawing back using the getItem method 
![image](https://github.com/user-attachments/assets/191ec51e-14e8-411f-ac93-0f9a7af8f070)
![image](https://github.com/user-attachments/assets/1d6b2113-c6ee-4d71-b3e5-f653cfa048f0)

**Comment by zeeldadhaniya1895** [comment]
@kavya020805 I already assigned issue #6 to you so pls complete that.

**Comment by atik-7866** [comment]
@zeeldadhaniya1895 Pls assign me this issue

**Comment by zeeldadhaniya1895** [comment]
@atik-7866, I am assigning this issue to you do your best !

**Comment by zeeldadhaniya1895** [comment]
@atik-7866 well done 👍

**Comment by zeeldadhaniya1895** [comment]
@atik-7866 the file name is being saved but the color and brush size are not you stored in local storage but they are not reassigned after reload please check it
